### PR TITLE
Add managing optolink adapter at URL / Add new channels/things

### PR DESCRIPTION
**Pull request by Sbried**
Optolink adapters behind an IP-serial converter (i.e. Lantronix XPort) can be included by adding an IP:port string as tty in the optolink.xml file.
I included an example-xml under src/main/resources.
Furthermore my Vitotronic_200_Typ_HO1 uses different things/channels. This is also included in the example-xml.

### CODE REVIEW

**Comment by steand** [comment]
@Sbried 
Thanks for your PR.
I need little time for retesting and merging. (my IDE is down at time; Hardware change)

@Sbried: did you use openhab 2 and do you wish that I add your now channels to the binding?

**Comment by Sbried** [comment]
@steand 
please test and advise possible improvements especially with exceptions. With Java I´m just starting ....
Yes, I use openhab2 and already rose the issue [1838](https://github.com/openhab/openhab2-addons/issues/1838) and forked. I will place a pull request once I´m done with the changes.

**Comment by steand** [comment]
@Sbried 
I am not sure if you has the rights to make a PR in openhab 2. My understanding is that only project members be able to do this. 
Please be free to contact me if you need help.
Regards Stefan

**Comment by Sbried** [comment]
@steand 
thanks for the hint. I couldn´t find anything contradictory on [contributing](http://docs.openhab.org/developers/contributing/contributing).


@kaikreuzer
Maybe you can clarify if any prerequisites (being project member) have to be fulfilled for making PRs in openhab 2?

**Comment by kaikreuzer** [comment]
> Maybe you can clarify if any prerequisites (being project member) have to be fulfilled for making PRs in openhab 2?

No! Anybody is welcome to create PRs against the openHAB repos!

**Pull request merged**
